author: BuxianChen
title: Blogs
email: buxian6@gmail.com
description: >-
  Some blogs.
baseurl: ""
url: ""
github_username: BuxianChen

markdown: kramdown

kramdown:
  input: GFM
  # parse_block_html: true
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-drawio

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      use_math: true
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      use_math: true

collections:
  drafts:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
